/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class main_GameState */

#ifndef _Included_main_GameState
#define _Included_main_GameState
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     main_GameState
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_main_GameState_init__
        (JNIEnv *, jobject);

/*
 * Class:     main_GameState
 * Method:    init
 * Signature: ([Lmain/GamePawnType;Lmain/GamePlayerType;)V
 */
JNIEXPORT void JNICALL Java_main_GameState_init___3Lmain_GamePawnType_2Lmain_GamePlayerType_2
        (JNIEnv *, jobject, jobjectArray, jobject);

/*
 * Class:     main_GameState
 * Method:    process
 * Signature: (Lmain/GamePosition;Lmain/GamePosition;)Lmain/GameMoveResult;
 */
JNIEXPORT jobject JNICALL Java_main_GameState_process
        (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     main_GameState
 * Method:    get
 * Signature: (Lmain/GamePosition;)Lmain/GamePawnType;
 */
JNIEXPORT jobject JNICALL Java_main_GameState_get
        (JNIEnv *, jobject, jobject);

/*
 * Class:     main_GameState
 * Method:    reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_main_GameState_reset
        (JNIEnv *, jobject);

/*
 * Class:     main_GameState
 * Method:    getCurrentPlayer
 * Signature: ()Lmain/GamePlayerType;
 */
JNIEXPORT jobject JNICALL Java_main_GameState_getCurrentPlayer
        (JNIEnv *, jobject);

/*
 * Class:     main_GameState
 * Method:    getWhitePawnsAmount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_main_GameState_getWhitePawnsAmount
        (JNIEnv *, jobject);

/*
 * Class:     main_GameState
 * Method:    getBlackPawnsAmount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_main_GameState_getBlackPawnsAmount
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
